### ISSUE TITLE
This forked repo does not honor original license

### ISSUE THREAD

**Issue by stephencelis** [Incetro/verse#1]
Hi there! We've found that several repos in the @Incetro organization are forks of repos from our @pointfreeco organization. It's totally fine to fork our work, but our MIT license requires you to preserve the original copyright and license. We would also appreciate credit and links to the original repositories.

Here's a list of all the repos that do not currently honor the original license:

- https://github.com/Incetro/combine-schedulers
    - Forked from: https://github.com/pointfreeco/combine-schedulers
- https://github.com/Incetro/verse-core-motion
    - Forked from: https://github.com/pointfreeco/composable-core-motion
- https://github.com/Incetro/verse-core-location
    - Forked from: https://github.com/pointfreeco/composable-core-location
- https://github.com/Incetro/enum-key-paths
    - Forked from: https://github.com/pointfreeco/swift-case-paths
- https://github.com/Incetro/verse
    - Forked from: https://github.com/pointfreeco/swift-composable-architecture
- https://github.com/Incetro/xctest-interface-adapter
    - Forked from: https://github.com/pointfreeco/xctest-dynamic-overlay

**Comment by stephencelis** [comment]
@monession Just making sure you saw this?

**Comment by monession** [comment]
@stephencelis 

I am very sorry for not seeing your message as soon as you wrote it. Can you check if I have mentioned your authorship correctly?  Thank you so much for your ideas and your work!

**Comment by stephencelis** [comment]
@monession Thanks! If you'd like to discuss the reasons for forking our repos rather than using our libraries directly, we'd love to know why. If, for example, we aren't covering certain things that you would like the libraries to cover.

**Comment by monession** [comment]
> @monession Thanks! If you'd like to discuss the reasons for forking our repos rather than using our libraries directly, we'd love to know why. If, for example, we aren't covering certain things that you would like the libraries to cover.

We have our own vision of how to adapt composable architecture for our projects, which is based on different architectural principles. Now we are trying to study your work in detail in order to build a mechanism for our company out of them. Later we will add many useful things to these repos and I can write to you when we do it, if you want to know
